"""RSS curation pipeline for Korean activist-investing news."""

__all__ = [
    "config",
    "benchmark_candidates",
    "event_identity",
    "fetch",
    "normalize",
    "dates",
    "relevance",
    "dedupe",
    "cluster",
    "rss_writer",
    "state",
    "telegram_publisher",
    "publish_outbox",
    "governance_publisher",
    "governance_site",
    "operation_mode",
    "label_agreement",
    "release_gate",
    "telegram_dashboard",
    "telegram_sources",
    "telegram_db_sync",
    "telegram_smoke_test",
]
